### ISSUE TITLE
T: Maquetación de componentes comunes y variables

### ISSUE THREAD

**Issue by elenaJO** [elenaJO/reto-seguro-vehicular#1]
**Overview**
Maquetación de componentes comunes y variables

**Issues**

- [x] Agregar variables globales #8
- [x] Agrego imágenes #9
- [x] Maquetación de botones #10
- [x] Maquetación de inputs y selectores #11
- [x] Maquetación de checkbox y switch #12
- [x] Maquetación footer #13
