### ISSUE TITLE
T: Maquetación Arma Plan

### ISSUE THREAD

**Issue by elenaJO** [elenaJO/reto-seguro-vehicular#3]
**Overview**
Maquetación Arma Plan 

**Issues**

- [x] Maquetación sección pasos #25 
- [x] Maquetación sección cobertura #26
- [x] Maquetación sección contador #27 
- [x] Maquetación agrega/quita cobertura #28
- [x] Maquetación pago #29
